### ISSUE TITLE
Report about MT7630e WiFi adapter

### ISSUE THREAD

**Issue by Ahmed-E-86** [linuxhw/HWInfo#3]
According to your website `MEDIATEK MT7630e 802.11bgn Wireless Network Adapter` is supported starting from kernel 4.20, but it is not supported with the newer kernels.

https://linux-hardware.org/?id=pci:14c3-7630-103c-197c

In other drivers you have mentioned these repos:
https://github.com/kuba-moo/mt7630e
https://github.com/lwfinger/mt7630

But both are outdated, and there is a newer repo:
https://github.com/neurobin/MT7630E

**Comment by linuxhw** [comment]
Fixed. Thanks for your help!
