### ISSUE TITLE
[question] How to get all dumps of hw-probe, not only bad Linux-compatibility?

### ISSUE THREAD

**Issue by Bogdan107** [linuxhw/HWInfo#4]
I want to create BogoMIPS rating of CPUs.

Table contain this columns and may contain any others:
- Vendor ID
- CPU Family
- Model & Model Name
- Flags
- CPU frequency min/max
- Cache size (L1, L2, L3)
- Units/Processors count
- BogoMips / Per one core
- BogoMips / Total

I want to parse maximum dumps for this reasons:
- create CPU's BogoMIPS rating;
- create historical changes of BogoMIPS values (min, max, median, etc).

How can I get all dumps of hw-probe, not only "bad Linux-compatibility"?

**Comment by linuxhw** [comment]
Do you need `lscpu` logs dumped to GitHub for this?

Like this one https://linux-hardware.org/?probe=2b76ee0822&log=lscpu

**Comment by linuxhw** [comment]
Are BogoMips depend on motherboard installed?

**Comment by linuxhw** [comment]
Need to decide how to organize the catalog - by board model or by CPU model.

**Comment by Bogdan107** [comment]
> Are BogoMips depend on motherboard installed?

BogoMIPS depend on CPU, but little bit effect has BIOS and early microcode.

In my case:
```
dmesg | grep -i -e "cpu(s)" -e bogomips
[    0.376108] Calibrating delay loop (skipped), value calculated using timer frequency.. 5988.78 BogoMIPS (lpj=2994392)
[    0.538167] smpboot: Total of 12 processors activated (71865.40 BogoMIPS)
```
12 cores * 5988.78 BogoMIPS = 71865,36 BogoMIPS * 12 cores
But dmesg says, that 12 cores have 71865.40 BogoMIPS.

Delta: 71865.40 - (12 * 5988.78) = 71865.40 - 71865,36 = 0,04

For "BogoMIPS rating" enough info by CPU model.

**Comment by Bogdan107** [comment]
> Do you need `lscpu` logs dumped to GitHub for this?
> 
> Like this one https://linux-hardware.org/?probe=2b76ee0822&log=lscpu

I need just files, no preffered distribution variant.
It is may be simple high-compressed archives by year for previous years, and by months for current year.

**Comment by linuxhw** [comment]
> > Do you need `lscpu` logs dumped to GitHub for this?
> > Like this one https://linux-hardware.org/?probe=2b76ee0822&log=lscpu
> 
> I need just files.
> My preffered distribution variant is simple high-compressed archives by year for previous years, and by months for current year (only finished months).

I'll prepare the package with `lscpu` reports per model in a week. You'll need to order models by family / model and stepping numbers.

**Comment by linuxhw** [comment]
Please see https://github.com/linuxhw/LsCPU

**Comment by Bogdan107** [comment]
> Please see https://github.com/linuxhw/LsCPU

It's cool!

**Comment by linuxhw** [comment]
> > Please see https://github.com/linuxhw/LsCPU
> 
> It's cool!
> I will be more happy, if values in Model column was in full form, without "...".

Fixed
