### ISSUE TITLE
Arch Package conflict

### ISSUE THREAD

**Issue by arghyagod-coder** [linuxhw/HWInfo#5]
```
error: failed to commit transaction (conflicting files)
hwinfo: /sbin exists in filesystem (owned by filesystem)
```

The package conflicts with filesystem (possibly problem in packaging as mentioned in https://bugs.archlinux.org/task/72440 )

Pls fix it asap,

**Comment by linuxhw** [comment]
Hello!

Proper repository for hwinfo utility is: https://github.com/openSUSE/hwinfo

This is the repository of hwinfo reports.
